name: Docker Build and IBM Cloud Deploy

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag joaopedropp/interstella5555
    - name: Docker Login
      run: docker login -u joaopedropp -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      run: docker push joaopedropp/interstella5555
