name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag joaopedropp/interstella5555
    - name: Docker Login
      uses: docker/login-action@main
      with:
        username: joaopedropp
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      run: docker push joaopedropp/interstella5555


